/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main

import org.junit.After
import org.junit.Before
import kotlin.test.Test
import kotlin.test.assertEquals

import java.net.URL

import org.openqa.selenium.WebDriver
import org.openqa.selenium.chrome.ChromeOptions
import org.openqa.selenium.remote.RemoteWebDriver

class KotlinlangPageTest {
    private lateinit var driver: WebDriver
    private lateinit var page: KotlinlangPage

    // This happens before each test
    @Before
    fun setup() {
        // That is a default port and url for Selenium Hub
        val url = URL("http://localhost:4444/wd/hub")

        // Instantiate RemoteWebDriver with ChromeOptions
        driver = RemoteWebDriver(url, ChromeOptions())
        // Get page instance
        page = KotlinlangPage(driver)
    }

    // This happens after each test
    @After
    fun teardown() {
        // Close after each test
        driver.close()
    }

    @Test
    fun `display "Kotlin" in logo`() {
        // Visit kotlinlang.org website
        page.open()
        // Test, if the found element's text is "Kotlin"
        assertEquals(page.getLogoText(), "Kotlin")
    }
}

